version: '3.1'
services:

    web:
        image: 'nginx:alpine'
        working_dir: /app
        volumes:
            - './app:/app'
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '${HTTP_PORT}:80'
        depends_on:
            - app

    db:
        image: 'mariadb:latest'
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DB_NAME}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - '${MYSQL_PORT}:3306'

    app:
        build: docker/php-fpm
        working_dir: /app
        ports:
            - '4200:4200'
        volumes:
            - './app:/app'
        depends_on:
            - db
        environment:
            - MYSQL_HOST=db
            - MYSQL_DATABASE=${MYSQL_DB_NAME}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
